export const cityNames = [
  'Aberdeen',
  'Abilene',
  'Afghanistan',
  'Akron',
  'Aland Islands',
  'Albania',
  'Albany',
  'Albuquerque',
  'Alexandria',
  'Algeria',
  'Allentown',
  'Amarillo',
  'American Samoa',
  'Anaheim',
  'Anchorage',
  'Andorra',
  'Angola',
  'Anguilla',
  'Ann Arbor',
  'Antarctica',
  'Antigua and Barbuda',
  'Antioch',
  'Apple Valley',
  'Appleton',
  'Argentina',
  'Arlington',
  'Armenia',
  'Aruba',
  'Arvada',
  'Asheville',
  'Athens',
  'Atlanta',
  'Atlantic City',
  'Augusta',
  'Aurora',
  'Austin',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas (the)',
  'Bahrain',
  'Bakersfield',
  'Baltimore',
  'Bangladesh',
  'Barbados',
  'Barnstable',
  'Baton Rouge',
  'Beaumont',
  'Bel Air',
  'Belarus',
  'Belgium',
  'Belize',
  'Bellevue',
  'Benin',
  'Berkeley',
  'Bermuda',
  'Bethlehem',
  'Bhutan',
  'Billings',
  'Birmingham',
  'Bloomington',
  'Boise City',
  'Boise',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bonita Springs',
  'Bosnia and Herzegovina',
  'Boston',
  'Botswana',
  'Boulder',
  'Bouvet Island',
  'Bradenton',
  'Brazil',
  'Bremerton',
  'Bridgeport',
  'Brighton',
  'British Indian Ocean Territory (the)',
  'Brownsville',
  'Brunei Darussalam',
  'Bryan',
  'Buffalo',
  'Bulgaria',
  'Burbank',
  'Burkina Faso',
  'Burlington',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cambridge',
  'Cameroon',
  'Canada',
  'Canton',
  'Cape Coral',
  'Carrollton',
  'Cary',
  'Cathedral City',
  'Cayman Islands (the)',
  'Cedar Rapids',
  'Central African Republic (the)',
  'Chad',
  'Champaign',
  'Chandler',
  'Charleston',
  'Charlotte',
  'Chattanooga',
  'Chesapeake',
  'Chicago',
  'Chile',
  'China',
  'Christmas Island',
  'Chula Vista',
  'Cincinnati',
  'Clarke County',
  'Clarksville',
  'Clearwater',
  'Cleveland',
  'Cocos (Keeling) Islands (the)',
  'College Station',
  'Colombia',
  'Colorado Springs',
  'Columbia',
  'Columbus',
  'Comoros (the)',
  'Concord',
  'Congo (the Democratic Republic of the)',
  'Congo (the)',
  'Cook Islands (the)',
  'Coral Springs',
  'Corona',
  'Corpus Christi',
  'Costa Mesa',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Dallas',
  'Daly City',
  'Danbury',
  'Davenport',
  'Davidson County',
  'Dayton',
  'Daytona Beach',
  'Deltona',
  'Denmark',
  'Denton',
  'Denver',
  'Des Moines',
  'Detroit',
  'Djibouti',
  'Dominica',
  'Dominican Republic (the)',
  'Downey',
  'Duluth',
  'Durham',
  'Ecuador',
  'Egypt',
  'El Monte',
  'El Paso',
  'El Salvador',
  'Elizabeth',
  'Elk Grove',
  'Elkhart',
  'Equatorial Guinea',
  'Erie',
  'Eritrea',
  'Escondido',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Eugene',
  'Evansville',
  'Fairfield',
  'Falkland Islands (the) [Malvinas]',
  'Fargo',
  'Faroe Islands (the)',
  'Fayetteville',
  'Fiji',
  'Finland',
  'Fitchburg',
  'Flint',
  'Fontana',
  'Fort Collins',
  'Fort Lauderdale',
  'Fort Smith',
  'Fort Walton Beach',
  'Fort Wayne',
  'Fort Worth',
  'France',
  'Frederick',
  'Fremont',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories (the)',
  'Fresno',
  'Fullerton',
  'Gabon',
  'Gainesville',
  'Gambia (the)',
  'Garden Grove',
  'Garland',
  'Gastonia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Gilbert',
  'Glendale',
  'Grand Prairie',
  'Grand Rapids',
  'Grayslake',
  'Greece',
  'Green Bay',
  'GreenBay',
  'Greenland',
  'Greensboro',
  'Greenville',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea-Bissau',
  'Guinea',
  'Gulfport-Biloxi',
  'Guyana',
  'Hagerstown',
  'Haiti',
  'Hampton',
  'Harlingen',
  'Harrisburg',
  'Hartford',
  'Havre de Grace',
  'Hayward',
  'Heard Island and McDonald Islands',
  'Hemet',
  'Henderson',
  'Hesperia',
  'Hialeah',
  'Hickory',
  'High Point',
  'Hollywood',
  'Holy See (the)',
  'Honduras',
  'Hong Kong',
  'Honolulu',
  'Houma',
  'Houston',
  'Howell',
  'Hungary',
  'Huntington Beach',
  'Huntington',
  'Huntsville',
  'Iceland',
  'Independence',
  'India',
  'Indianapolis',
  'Indonesia',
  'Inglewood',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Irvine',
  'Irving',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jackson',
  'Jacksonville',
  'Jamaica',
  'Japan',
  'Jefferson',
  'Jersey City',
  'Jersey',
  'Johnson City',
  'Joliet',
  'Jordan',
  'Kailua',
  'Kalamazoo',
  'Kaneohe',
  'Kansas City',
  'Kazakhstan',
  'Kennewick',
  'Kenosha',
  'Kenya',
  'Killeen',
  'Kiribati',
  'Kissimmee',
  'Knoxville',
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  'Lacey',
  'Lafayette',
  'Lake Charles',
  'Lakeland',
  'Lakewood',
  'Lancaster',
  'Lansing',
  'Laredo',
  'Las Cruces',
  'Las Vegas',
  'Latvia',
  'Layton',
  'Lebanon',
  'Leominster',
  'Lesotho',
  'Lewisville',
  'Lexington',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lincoln',
  'Lithuania',
  'Little Rock',
  'Long Beach',
  'Lorain',
  'Los Angeles',
  'Louisville',
  'Lowell',
  'Lubbock',
  'Luxembourg',
  'Macao',
  'Macon',
  'Madagascar',
  'Madison',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Manchester',
  'Marina',
  'Marshall Islands (the)',
  'Martinique',
  'Marysville',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'McAllen',
  'McHenry',
  'Medford',
  'Melbourne',
  'Memphis',
  'Merced',
  'Mesa',
  'Mesquite',
  'Mexico',
  'Miami',
  'Micronesia (Federated States of)',
  'Milwaukee',
  'Minneapolis',
  'Miramar',
  'Mission Viejo',
  'Mobile',
  'Modesto',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Monroe',
  'Montenegro',
  'Monterey',
  'Montgomery',
  'Montserrat',
  'Moreno Valley',
  'Morocco',
  'Mozambique',
  'Murfreesboro',
  'Murrieta',
  'Muskegon',
  'Myanmar',
  'Myrtle Beach',
  'Namibia',
  'Naperville',
  'Naples',
  'Nashua',
  'Nashville',
  'Nauru',
  'Nepal',
  'Netherlands (the)',
  'New Bedford',
  'New Caledonia',
  'New Haven',
  'New London',
  'New Orleans',
  'New York City',
  'New York',
  'New Zealand',
  'Newark',
  'Newburgh',
  'Newport News',
  'Nicaragua',
  'Niger (the)',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Norfolk',
  'Normal',
  'Norman',
  'North Charleston',
  'North Las Vegas',
  'North Port',
  'Northern Mariana Islands (the)',
  'Norwalk',
  'Norway',
  'Norwich',
  'Oakland',
  'Ocala',
  'Oceanside',
  'Odessa',
  'Ogden',
  'Oklahoma City',
  'Olathe',
  'Olympia',
  'Omaha',
  'Oman',
  'Ontario',
  'Orange',
  'Orem',
  'Orlando',
  'Overland Park',
  'Oxnard',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Palm Bay',
  'Palm Springs',
  'Palmdale',
  'Panama City',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Pasadena',
  'Paterson',
  'Pembroke Pines',
  'Pensacola',
  'Peoria',
  'Peru',
  'Philadelphia',
  'Philippines (the)',
  'Phoenix',
  'Pitcairn',
  'Pittsburgh',
  'Plano',
  'Poland',
  'Pomona',
  'Pompano Beach',
  'Port Arthur',
  'Port Orange',
  'Port Saint Lucie',
  'Port St. Lucie',
  'Portland',
  'Portsmouth',
  'Portugal',
  'Poughkeepsie',
  'Providence',
  'Provo',
  'Pueblo',
  'Puerto Rico',
  'Punta Gorda',
  'Qatar',
  'Racine',
  'Raleigh',
  'Rancho Cucamonga',
  'Reading',
  'Redding',
  'Reno',
  'Republic of North Macedonia',
  'Réunion',
  'Richland',
  'Richmond County',
  'Richmond',
  'Riverside',
  'Roanoke',
  'Rochester',
  'Rockford',
  'Romania',
  'Roseville',
  'Round Lake Beach',
  'Russian Federation (the)',
  'Rwanda',
  'Sacramento',
  'Saginaw',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Louis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Paul',
  'Saint Petersburg',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Salem',
  'Salinas',
  'Salt Lake City',
  'Samoa',
  'San Antonio',
  'San Bernardino',
  'San Buenaventura',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Marino',
  'Santa Ana',
  'Santa Barbara',
  'Santa Clara',
  'Santa Clarita',
  'Santa Cruz',
  'Santa Maria',
  'Santa Rosa',
  'Sao Tome and Principe',
  'Sarasota',
  'Saudi Arabia',
  'Savannah',
  'Scottsdale',
  'Scranton',
  'Seaside',
  'Seattle',
  'Sebastian',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Shreveport',
  'Sierra Leone',
  'Simi Valley',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Sioux City',
  'Sioux Falls',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Bend',
  'South Georgia and the South Sandwich Islands',
  'South Lyon',
  'South Sudan',
  'Spain',
  'Spartanburg',
  'Spokane',
  'Springdale',
  'Springfield',
  'Sri Lanka',
  'St. Louis',
  'St. Paul',
  'St. Petersburg',
  'Stamford',
  'Sterling Heights',
  'Stockton',
  'Sudan (the)',
  'Sunnyvale',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syracuse',
  'Syrian Arab Republic',
  'Tacoma',
  'Taiwan',
  'Tajikistan',
  'Tallahassee',
  'Tampa',
  'Tanzania, United Republic of',
  'Temecula',
  'Tempe',
  'Thailand',
  'Thornton',
  'Thousand Oaks',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Toledo',
  'Tonga',
  'Topeka',
  'Torrance',
  'Trenton',
  'Trinidad and Tobago',
  'Tucson',
  'Tulsa',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (the)',
  'Tuscaloosa',
  'Tuvalu',
  'Tyler',
  'Uganda',
  'Ukraine',
  'United Arab Emirates (the)',
  'United Kingdom of Great Britain and Northern Ireland (the)',
  'United States Minor Outlying Islands (the)',
  'United States of America (the)',
  'Uruguay',
  'Utica',
  'Uzbekistan',
  'Vallejo',
  'Vancouver',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Vero Beach',
  'Victorville',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Virginia Beach',
  'Visalia',
  'Waco',
  'Wallis and Futuna',
  'Warren',
  'Washington',
  'Waterbury',
  'Waterloo',
  'West Covina',
  'West Valley City',
  'Western Sahara',
  'Westminster',
  'Wichita',
  'Wilmington',
  'Winston',
  'Winter Haven',
  'Worcester',
  'Yakima',
  'Yemen',
  'Yonkers',
  'York',
  'Youngstown',
  'Zambia',
  'Zimbabwe',
  "Côte d'Ivoire",
  "Korea (the Democratic People's Republic of)",
  "Lao People's Democratic Republic (the)",
]
